const Map<String, String> ar = {
  "ju":"الجامعة الأرنية",
  "news":"أخبار",
  "seeMore":"شاهد المزيد",
  "home":"الصفحة الرئيسة",
  "collages":"الكليات",
  "saved":"المفضلة",
  "profile":"الحساب",
  "savedNews":"الأخبار المفضلة",
  "userName":"اسم المستخدم",
  "collegeName":"اسم الكلية",
  "settings":"إعدادات",
  "logout":"تسجيل خروج",
  "aboutUs":"من نحن",
  "language":"اللغة",
  "themeMode":"تغيير المظهر",
  "notifications":"إشعارات",
  "login":"تسجيل الدخول",
  "emailAddress":"البريد الإلكتروني",
  "password":"كلمة المرور",
  "seeAll":"إظهار الكل",
  "recentNews":"آخر الأخبار",
  "universityNews":"أخبار الجامعة",
  "play":"تشغيل",
  "collegeNews":"أخبار الكلية",
  "search...":"بحث...",
  "position":"وضع",
  "changeLanguage":"تغيير اللغة",
  "emailMustNotBeEmpty":"الرجاء ادخال البريد الالكتروني",
  "passwordMustNotBeEmpty":"الرجاء ادخال كلمة المرور",
  "cannotFindAccount":"الحساب غير موجود",
  "cannotFindAnAccountWith":"لا يوجد حساب بالبريد الالكتروني ",
  "pleaseEnterCorrectEmail":"الرجاء ادخال بريد الكتروني صحيح",
  "ok":"موافق",
  "incorrectPassword":"كلمة المرور غير صحيحة",
  "thePasswordEnteredIsIncorrect":"كلمة المرور المدخلة غير صحيحة",
"save":"حفظ",
  "AreYouSureYouWantToLogOut":"هل أنت متأكد أنك تريد تسجيل الخروج ؟",
  "cancel":"إلغاء",
};
