const Map<String, String> en = {
  "ju":"JU",
  "news":"News",
  "seeMore":"See More",
  "home":"Home",
  "collages":"Collages",
  "saved":"Saved",
  "profile":"Profile",
  "savedNews":"Saved News",
  "userName":"User Name",
  "collegeName":"College Name",
  "settings":"Settings",
  "logout":"Logout",
  "aboutUs":"About Us",
  "language":"Language",
  "themeMode":"Theme Mode",
  "notifications":"Notifications",
  "login":"Login",
  "emailAddress":"Email Address",
  "password":"Password",
  "seeAll":"See All",
  "recentNews":"Recent News",
  "universityNews":"University News",
  "play":"Play",
  "collegeNews":"College News",
  "search...":"Search...",
  "position":"Position",
  "changeLanguage":"Change Language",
  "emailMustNotBeEmpty":"Email must not be Empty!",
"passwordMustNotBeEmpty":"Password must not be Empty!",
  "cannotFindAccount":"Cannot Find Account",
  "cannotFindAnAccountWith":"Can't Find An Account With",
  "pleaseEnterCorrectEmail":"Please Enter Correct Email",
  "ok":"Ok",
  "incorrectPassword":"Incorrect Password",
  "thePasswordEnteredIsIncorrect":"The Password Entered Is Incorrect",
  "save":"Save",
  "AreYouSureYouWantToLogOut":"Are You Sure You Want To LogOut",
  "cancel":"Cancel",
};
